"""Domain models and shot-analysis rules."""

from shotsight2.domain.jobs import ClaimedJob, QueueMessage
from shotsight2.domain.persistence import (
    AnalysisJob,
    AnalysisRun,
    AnalysisStage,
    Artifact,
    BackupMetadata,
    BallTrack,
    Calibration,
    CameraSegment,
    EffectiveShotAttempt,
    JobStatus,
    PlayerTrack,
    ReviewCorrection,
    ReviewStatus,
    RunStatus,
    ShotAttempt,
    ShotLocation,
    ShotOutcome,
    Video,
    VideoStatus,
)
from shotsight2.domain.statistics import (
    LocationGroupSummary,
    PlayerShotSummary,
    ReviewStatusSummary,
    ShotChartPoint,
    ShotSummary,
    ShotTypeSummary,
    VideoStatistics,
    calculate_video_statistics,
)

__all__ = [
    "AnalysisJob",
    "AnalysisRun",
    "AnalysisStage",
    "Artifact",
    "BackupMetadata",
    "BallTrack",
    "Calibration",
    "CameraSegment",
    "ClaimedJob",
    "EffectiveShotAttempt",
    "JobStatus",
    "LocationGroupSummary",
    "PlayerTrack",
    "PlayerShotSummary",
    "QueueMessage",
    "ReviewCorrection",
    "ReviewStatus",
    "ReviewStatusSummary",
    "RunStatus",
    "ShotAttempt",
    "ShotChartPoint",
    "ShotLocation",
    "ShotOutcome",
    "ShotSummary",
    "ShotTypeSummary",
    "VideoStatistics",
    "Video",
    "VideoStatus",
    "calculate_video_statistics",
]
